openapi: 3.0.3
info:
  version: '1'
  title: Generate thumbnails API
  description: API for generate thumbnails from an image
  license:
    name: MIT
servers:
  - url: https://localhost/v1
    description: Development server
  - url: https://thumbnail-generator/test/v1
    description: Testing server
paths:
  /images:
    post:
      summary: Upload an image
      description: Upload an image to generate the thumbnails
      operationId: uploadImage
      tags:
        - images
      requestBody:
        required: true
        content:
          image/jpeg:
            schema:
              $ref: '#/components/schemas/File'
            examples:
              image:
                $ref: '#/components/examples/ImageForUpload'
      responses:
        '200':
          $ref: '#/components/responses/ImageResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /images/{id}:
    get:
      summary: Get image by id
      description: Get an image by id
      operationId: getImage
      tags:
        - images
      parameters:
        - name: id
          in: path
          description: Image id
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ImageResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /thumbnails:
    get:
      summary: Get generated thumbnails
      description: 'Get all generated thumbnails'
      operationId: getThumbnails
      tags:
        - thumbnails
      parameters:
        - name: image_id
          in: query
          description: Image id
          required: true
          schema:
            type: string
        - name: size
          in: query
          description: Thumbnail size
          schema:
            $ref: '#/components/schemas/ThumbnailSize'
      responses:
        '200':
          $ref: '#/components/responses/ThumbnailsResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Error:
      type: object
      description: Schema for represents an error on system
      properties:
        code:
          type: string
          description: Code that identifies the error on the system
        message:
          type: string
          description: Message that explain the error
    File:
      description: Represents a file
      type: string
      format: binary
    ThumbnailSize:
      description: Thumbnail size
      type: string
      enum:
        - 400x300
        - 160x120
        - 120x120
    Image:
      type: object
      properties:
        id:
          type: string
          description: Identifier of image
        name:
          type: string
          description: Name of image
        status:
          type: string
          description: Status of image
          enum:
            - UPLOADED
            - GENERATING_THUMBNAILS
            - THUMBNAILS_GENERATED
        url:
          type: string
          description: Url of image
    Thumbnail:
      type: object
      properties:
        id:
          type: string
          description: Identifier of thumbnail
        size:
          $ref: '#/components/schemas/ThumbnailSize'
        url:
          type: string
          description: Url of thumbnail
  responses:
    ValidationError:
      description: Error generated by validations on the input of the endpoint
      content:
        application/json:
          schema:
            type: array
            description: Array with errors
            items:
              $ref: '#/components/schemas/Error'
          examples:
            GeneralValidationError:
              $ref: '#/components/examples/ValidationErrorResponse'
    InternalServerError:
      description: Error generated by an unexpected exception on system
      content:
        application/json:
          schema:
            type: array
            description: Array with errors
            items:
              $ref: '#/components/schemas/Error'
          examples:
            InternalServerError:
              $ref: '#/components/examples/InternalServerErrorResponse'
    NotFoundError:
      description: Error generated by the resource not exists
      content:
        application/json:
          schema:
            type: array
            description: Array with errors
            items:
              $ref: '#/components/schemas/Error'
          examples:
            NotFoundError:
              $ref: '#/components/examples/NotFoundErrorResponse'
    ImageResponse:
      description: Your image has been uploaded successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              image:
                $ref: '#/components/schemas/Image'
          examples:
            ImageResponse:
              $ref: '#/components/examples/ImageResponse'
    ThumbnailsResponse:
      description: Thumbnails retrieved with success
      content:
        application/json:
          schema:
            type: object
            properties:
              thumbnails:
                type: array
                description: Array of thumbnails
                items:
                  $ref: '#/components/schemas/Thumbnail'
          examples:
            ThumbanailsResponse:
              $ref: '#/components/examples/ThumbnailsResponse'
  examples:
    ValidationErrorResponse:
      summary: This is an example of validation error
      value:
        errors:
          - code: "1000"
            message: The file uploaded is not a valid jpeg file
    InternalServerErrorResponse:
      summary: This is an example of internal server error
      value:
        errors:
          - code: "500"
            message: Has been occurred unexpected error, please retry again later
    NotFoundErrorResponse:
      summary: This is an example of not found error
      value:
        errors:
          - code: "404"
            message: The image not exists
    ImageForUpload:
      summary: This is an example of image for upload
      externalValue: 'https://media-exp1.licdn.com/dms/image/C4E0BAQEmZ6-RlFCDNA/company-logo_200_200/0/1558041156098?e=2159024400&v=beta&t=YwiI8-Lol20SVbZXDGRp2keAKjtIuwLej4lvQqGA4AI'
    ImageResponse:
      summary: This is an example of image response
      value:
        image:
          id: XXXXXXXXXXX
          name: sinapsis-logo.jpeg
          status: THUMBNAILS_GENERATED
          url: https://s3-example.com
    ThumbnailsResponse:
      summary: This is an example of thumbnails response
      value:
        thumbnails:
          - id: XXXXXXXXXXX
            size: 400x300
            url: https://s3-example.com
          - id: XXXXXXXXXXX
            size: 400x300
            url: https://s3-example.com
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - auth: []

